version: '3.7'

services:
  api:
    restart: always
    build: ./api
    container_name: api
    command: yarn start
    volumes:
      - ./api:/app/api
    ports:
      - 8000:8000
  frontend:
    restart: always
    build: ./client
    container_name: client
    command: yarn start
    volumes:
      - ./client:/app/client
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: db
    ports:
      - '27017:27017'

volumes:
  node_modules:
