GET http://localhost:3000/courses

###

Get http://localhost:3000/courses/5d3e0db7cb4be0bfc4c25ff9

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "name": "Data Structures",
  "coi": "CS"
  "cn": 225
}

###
DELETE http://localhost:3000/courses/5d3e0db7cb4be0bfc4c25ff9

###
PATCH http://localhost:3000/courses/5d3e144ecb4be0bfc4c25ffa
Content-Type: application/json 

{
  "name": "Data Structures"
}